### ISSUE TITLE
Max CH water temeprature

### ISSUE THREAD

**Issue by SebuZet** [arthurrump/esphome-opentherm#22]
Hi,
First of all I would like to thanks for you work.
I'm trying to use it with my Immergas Victrix Tera 28 1 but it looks like CH max water point cannot be changed.
I've underfloor heating system and I wanted to change maximum water temperature in CH. It should be 40 degrees but this limit doesn't work. How can I set a max water temperature? Is it possible without recompilation of Opentherm library?

Thanks,
Seba

**Comment by wildekek** [comment]
My boiler does not allow setting the CH max water setpoint, but when you limit the values in the t_set output, it effectively does the same:
```
output:
  - platform: opentherm
    t_set:
      id: boiler_ch_setpoint
      min_value: 20
      max_value: 40
      zero_means_zero: true
```

Make sure you check out *actual* output water temperature of the boiler though, I get a few degrees of overshoot, don't want to damage those floors.
