### ISSUE TITLE
'remote-github' is not a git command error when I check/compile my .yml file

### ISSUE THREAD

**Issue by bucovaina** [arthurrump/esphome-opentherm#23]
May I first thank you endlessly for this custom component! I've been wanting this for a very long time. I ordered the opentherm thermostat 2 years ago and didn't use it yet. Now I took it from under the dust and to my big surprise, there was an esphome integration. This is gold!!

But my issue I have:
I use the yml file at the bottom (copy paste from an example I took here). I didn't change anything except for the external_components block. 

I use esphome 2023.9.3, with Python 3.11.2 in a venv which I activate when I want to do something with esphome. I'm not that big a user but so far it has worked very well for me on other projects.

But when I check the config of the yml file at the bottom, I get this:
```
(esphome) user@macbookuser:~/Documents/smarthome/esphome$ esphome config opentherm-esphome.yml 
INFO ESPHome 2023.9.3
INFO Reading configuration opentherm-esphome.yml...
INFO Cloning github://arthurrump/esphome-opentherm@main@None
Failed config

external_components: [source opentherm-esphome.yml:15]
  - 
    Cloning into '.esphome/external_components/8cae1e12'...
    git: 'remote-github' is not a git command. See 'git --help'.
    source: 
      type: git
      url: github://arthurrump/esphome-opentherm@main
(esphome) user@user:~/Documents/smarthome/esphome$ 
```
Before I also ran into no such compontent, then I read that you have to have a recent version of python (which seems to be so), so it can't be that problem I guess, or maybe too recent?

My yml file:
```
esphome:
  name: thermostat-pid-complete

external_components:
  - source:
      type: git
      url: github://arthurrump/esphome-opentherm@main
esp8266:
  board: d1_mini

logger:

api:
ota:
wifi:
  ap:
    ssid: "Thermostat"
    password: "MySecretThemostat"
captive_portal:

opentherm:
  ch_enable: true
  dhw_enable: true

output:
  - platform: opentherm
    t_set:
      id: t_set
      min_value: 20
      max_value: 65
      zero_means_zero: true

sensor:
  - platform: opentherm
    rel_mod_level:
      name: "Boiler Relative modulation level"
    t_boiler:
      name: "Boiler water temperature"
    t_ret:
      name: "Boiler Return water temperature"  

  - platform: homeassistant
    id: ch_room_temperature
    entity_id: sensor.temperature
    filters: 
      # Push room temperature every second to update PID parameters
      - heartbeat: 1s  

binary_sensor:
  - platform: opentherm
    ch_active:
      name: "Boiler Central Heating active"
    dhw_active:
      name: "Boiler Domestic Hot Water active"
    flame_on:
      name: "Boiler Flame on"
    fault_indication:
      name: "Boiler Fault indication"
      entity_category: diagnostic
    diagnostic_indication:
      name: "Boiler Diagnostic event"
      entity_category: diagnostic

switch:
  - platform: opentherm
    ch_enable:
      name: "Boiler Central Heating enabled"
      mode: restore_default_on

climate:
  - platform: pid
    name: "Central heating"
    heat_output: t_set
    default_target_temperature: 20
    sensor: ch_room_temperature
    control_parameters: 
      kp: 0.4
      ki: 0.004
</code>
```
