### ISSUE TITLE
Only arduino framework supported

### ISSUE THREAD

**Issue by ChernyaevAN** [arthurrump/esphome-opentherm#28]
It looks like
```
in_pin:
out_pin:
```
works only in arduino framework.

This is the part of my YAML file:
```
esphome:
  name: opentherm
  friendly_name: OpenTherm
  platformio_options:
    board_build.f_flash: 40000000L
    board_build.flash_mode: dio
    board_build.flash_size: 4MB
    board_build.mcu: esp32c3
    board_build.variant: esp32c3
    board_build.f_cpu: 160000000L

esp32:
  board: lolin_c3_mini
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_FREERTOS_UNICORE: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_160: y
      CONFIG_ESP32_DEFAULT_CPU_FREQ_MHZ: "160"
      COMPILER_OPTIMIZATION_SIZE: y
      CONFIG_BT_BLE_50_FEATURES_SUPPORTED: y
      CONFIG_BT_BLE_42_FEATURES_SUPPORTED: y
      CONFIG_ESP_TASK_WDT: y
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "10"
    advanced:
      ignore_efuse_mac_crc: false
  variant: esp32c3

```
Can you correct it?
