### ISSUE TITLE
DIYLESS shield and temperature sensor

### ISSUE THREAD

**Issue by antonioste** [arthurrump/esphome-opentherm#31]
Hi,
I'm use DIYLESS master shield. This shield have a temperature sensor connect to pin 14. How I can set it in yaml instead of HA sensor?

thanks

**Comment by hannahdiels** [comment]
Edit: My bad, misread your question, I don't use the DIYLESS bluetooth temperature sensor, or are you saying there's also another temp sensor directly connected on pin 14?

This is what I use for DIYLESS:

```
esp32:
  board: wemos_d1_mini32
  framework:
    type: arduino

opentherm:
  # The pin numbers I found in the diyless thermostat shield source code
  in_pin: 21
  out_pin: 22

# And you'll want to point to this fork instead as this repo is pretty much unmaintained and no longer works
esphome:
  name: boiler  # HA device id
  friendly_name: Boiler
  platformio_options:
    lib_deps:  # required by freebear-nc/esphome-opentherm
      - https://github.com/freebear-nc/opentherm_library.git

external_components:
  - source: github://freebear-nc/esphome-opentherm

...
```

**Comment by hannahdiels** [comment]
You probably already found [this](https://github.com/diyless/home-assistant-opentherm-thermostat/blob/main/opentherm-ha/config.h#L25), but I would dig around in the ino to find out what it is exactly and configure the equivalent of that as a component in esphome, give it an id and then point opentherm to that id.

**Comment by vaggelanos** [comment]
You can do this to load the temperature:

```
one_wire:
  - platform: gpio
    pin: GPIO18
    id: ch_room_temperature_bus

sensor:
  - platform: dallas_temp
    id: ch_room_temperature
    update_interval: 60s
    one_wire_id: ch_room_temperature_bus
```

Adjust the pin accordingly.
